server:
  port: 8080
spring:
  application:
    name: log-web
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/video_log?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
      stat-view-servlet:
          allow:  true   #监控页面启动
#通用mappers配置
mapper:
  mappers: com.zh.web.dao.IBaseDao  #扫描基类接口
  identity: mysql
# mybatis 别名扫描
mybatis:
  type-aliases-package: com.zh.web.entity
  configuration:
    map-underscore-to-camel-case: true  #开启下划线转驼峰
  mapper-locations: classpath:mappers/*.xml
  #config-location: classpath:mybatis-config.xml
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
